### ISSUE TITLE
任我行的“任”字没有二声

### ISSUE THREAD

**Issue by arsenali** [rime/rime-terra-pinyin#1]
萌典中也查到了任字的二声，作姓氏的时候是二声，不过地球拼音里还没有加入

**Comment by arsenali** [comment]
李暠的暠字，汉典注音hao4，萌典注音gao3，地球拼音中只有gao3，是不是也加上hao4好一点呢

**Comment by arsenali** [comment]
我通过导入扩展词库的功能实现了这一功能，非常感谢作者的无私奉献，谢谢！

**Comment by rtlanceroad** [comment]
@arsenali 嗨。刚刚偶尔发现这个issue. 能不能基于你的词库，做个PR, 将"任"的导入? 如果你有的，这个库里面也没有，希望你能做些PR. : -)

**Comment by arsenali** [comment]
我一直在补充和完善地球拼音词库，请看我的主页

**Comment by kunki** [comment]
Rime[預設詞庫](https://github.com/rime/rime-essay/blob/master/essay.txt)中沒有「任我行」一詞，所以需要用戶自己組詞。
「任」的rén和rèn音都收了的。
