### ISSUE TITLE
请核准如下字的读音："关"等等

### ISSUE THREAD

**Issue by zaqzrh** [rime/rime-terra-pinyin#15]
@kunki @lotem
现代汉语词典、现代汉语规范词典 
漢語大词典、漢語大字典
汉典网http://www.zdic.net/ 
國際電腦漢字及異體字知識庫http://chardb.iis.sinica.edu.tw/
没有这些读音！
请核准如下字的读音：
-------------------------
关	xiao4	100%
备	yuan2	100%
权	you3	100%
义	cha1	99%
亲	zhen1	99%
奋	gang3	97%
开	jian1	95%
和	han4	70%
垃	le4	50%
捭	bo4	50%
椿	chun2	50%
甬	tong3	50%
宪	hun4	33%
宪	mao4	33%
猎	ji2	30%
吁	a2	5%
开	qian1	5%
吁	yu2	4%
奋	ben3	2.50%
祭	zha4	1%
吃	ji2	0%
嵌	kan3	0%
惜	xi2	0%
榜	peng4	0%
业	qiu1	
乡	yuan4	
亘	huan2	
冈	wang3	
圾	se4	
汉	nv4	
胆	dan4	
荣	ce4	
许	hao4	
邮	di2

**Comment by lotem** [comment]
感謝 PR。
題中列舉的信息不完全準確。需要進一步覈實。
例如：「和	han4」「惜	xi2」的讀音在
國際電腦漢字及異體字知識庫 http://chardb.iis.sinica.edu.tw/
萌典 https://www.moedict.tw/
可以查到。其他字我還沒有一一查證。

**Comment by Prcuvu** [comment]
> 圾	se4

这个当然是有的。垃圾在台标中读音为“lèsè”。
