### ISSUE TITLE
請問有辦法輸入間隔號（全形音界號）「・」嗎？

### ISSUE THREAD

**Issue by stevencch99** [rime/rime-terra-pinyin#25]
找不到相關文件說明如何輸入「・」間隔號 (Unicode character = fullwidth full stop, HTML = `&#65294;`)

使用 shift + 8 只能得到相似的「・」(Unicode character = katakana middle dot, HTML = `&#12539;`)；

感謝您的付出和努力！

**Comment by LEOYoon-Tsaw** [comment]
透過tera-pinyin_custom.yaml修改方案加入此符即可。

**Comment by lotem** [comment]
注意：
Unicode Character “．” (U+FF0E) 不是「間隔號」，而是 Fullwidth Full Stop，即全形西文句點。
間隔號是Unicode Character “·” (U+00B7) Middle Dot，沒有全形／半形之分。一般所謂全形半形對應的是ASCII字符。
標題中的字符是Unicode Character “・” (U+30FB) Katakana Middle Dot。

輸入全形西文句點的方法是：
[使用方案選單](https://github.com/rime/home/wiki/UserGuide#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%A1%88%E9%81%B8%E5%96%AE)切換「半角→全角」，再次切換「，。→，．」，然後敲<kbd>.</kbd>鍵。

**Comment by stevencch99** [comment]
@lotem 感謝說明！
我也順便更正標題的符號，那個間隔號是從《教育部重定標點符號手冊》複製來的，還不太清楚用法。
