### ISSUE TITLE
“攻击”、“狙击”等含“击”词语 的“击”字有“ji1”音。

### ISSUE THREAD

**Issue by poorich** [rime/rime-terra-pinyin#29]
“攻击”、“狙击”等含“击”词语 的“击”字有“ji1”音。

_Originally posted by @BinglunGe in https://github.com/rime/rime-terra-pinyin/issues/24#issuecomment-659251468_

「擊」字相關的詞語　表中不少（約150+條）是第二聲

**Comment by LEOYoon-Tsaw** [comment]
不止這個字，地球拼音主要取自臺灣國語注音，讀法都是國語讀音。
大陸哪有帶調拼音詞庫？在大陸根本沒人關心聲調，當然沒有相關材料可用。
最好找到有一定規模的大陸普通話帶調詞庫，一併加入，一個字一個字改不是個辦法。

**Comment by lotem** [comment]
​只有這個辦法。
導入其他詞庫不能解決問題。
需要把對該字註音的詞條刪除，但須保留其中需要標註其他多音字的詞條、對這些詞條標註「擊」的兩種讀音。

**Comment by LEOYoon-Tsaw** [comment]
這樣的字還多著呢

**Comment by lotem** [comment]
> 這樣的字還多著呢

​這就是現實。
亦即維護這個詞典的困難之處。
每加入一批數據都應當對包含多音字特別是異讀音進行干預。現存的問題源於之前導入數據時沒有做這項處理。

導入其他詞庫如果不經人工干預：無法保證每個數據數據源包含的詞條完全「對齊」，即不多不少包含相同的詞條，否則比其他來源多出的詞仍會缺失該數據源未收錄的異讀音，也就會出現現在發生的問題。

**Comment by lotem** [comment]
宜併入 #32
