### ISSUE TITLE
持续记录未被标注的大陆多音字读音

### ISSUE THREAD

**Issue by zhanghaozhecn** [rime/rime-terra-pinyin#31]
本人长期使用声调必打的方案。本问题用于长期记录遇到的未标注的大陆读音。

**Comment by zhanghaozhecn** [comment]
期/qi1，ji1/qi2，ji1
识/shi2，zhi4/shi4，zhi4

**Comment by zhanghaozhecn** [comment]
| 微 | 息
-- | -- | --
大陆 | wei1 | xi1
台湾 | wei2 | xi2

**Comment by sgalal** [comment]
这样太低效了，网上应该有现成的字表，或者编程对比一下

**Comment by lotem** [comment]
除了簡化字「识」只標註了`shi2`，以上其他幾個字的異讀音均已收錄。

**Comment by zhanghaozhecn** [comment]
> 除了簡化字「识」只標註了`shi2`，以上其他幾個字的異讀音均已收錄。

确实收录了，我在处理词库的时候错误地使用了合并重复项。

**Comment by zhanghaozhecn** [comment]
> 这样太低效了，网上应该有现成的字表，或者编程对比一下

似乎完整的异读字对照表格并不容易直接搜索到，有一些零碎的读音对照我先看看吧。不会编程，只能一个一个处理。

**Comment by zhanghaozhecn** [comment]
异读字本身的不同读音，还有一些词的读音标注了，但似乎没有标注完全。举个例子，“期”这个音只能打qi2 xian4，bu4 qi2 er2 yu4，不能打qi1 xian4，bu4 qi1 er2 yu4。
![image](https://user-images.githubusercontent.com/72417945/109353041-d1a30680-7849-11eb-952e-3e17d80999f5.png)
![image](https://user-images.githubusercontent.com/72417945/109353138-ebdce480-7849-11eb-9a0b-b2dc22e15bf4.png)
查看最近的terra.dict里面也有不少这样的词，只有少数被处理了。这样实际用的时候，只能把这些词的注音删掉，一个一个改又很麻烦。
![image](https://user-images.githubusercontent.com/72417945/109354130-4fb3dd00-784b-11eb-863a-cf476ca94bf2.png)

**Comment by lotem** [comment]
宜併入 https://github.com/rime/rime-terra-pinyin/issues/32
如果能夠先手動解決部分問題也行。

**Comment by zhanghaozhecn** [comment]
https://zh.wikipedia.org/wiki/%E6%B5%B7%E5%B3%BD%E5%85%A9%E5%B2%B8%E6%BC%A2%E8%AA%9E%E7%99%BC%E9%9F%B3%E5%B7%AE%E7%95%B0%E5%88%97%E8%A1%A8
权威资料不好找啊，只能按照维基百科上的这部分先批量删除一部分读音，剩下的只能交给作者了。

**Comment by dqwyy** [comment]
目前网上的资料确实难找，维基百科的那个条目可供参考，目前还在佛系更新中。
另外我觉得微软内部应该有字表，因为用微软注音输入法时，简体输入模式用的是普通话的读音。
