### ISSUE TITLE
“涌”字應作爲首選字。

### ISSUE THREAD

**Issue by i-ug-yang** [rime/rime-terra-pinyin#33]
輸入“yong xian”的時候，首選字是湧，但是理論上來講“涌”字更符合小篆構字，爲“水+甬”形。望參考，如若下次更新能有所調整是再好不過的😄

**Comment by lotem** [comment]
本項目其實只收錄字的註音，組詞的用字標準可追溯到上游項目 https://github.com/BYVoid/OpenCC。
OpenCC對這一組字的解釋爲：
https://github.com/BYVoid/OpenCC/blob/master/data/scheme/st_multi.txt#L171
如果認爲有必要調整，您可以移步 https://github.com/BYVoid/OpenCC/issues 繼續討論。

**Comment by i-ug-yang** [comment]
感謝


| |
李旭阳
|
|
13161228888@163.com
|
签名由网易邮箱大师定制


在2021年02月28日 15:24，居戎氏<notifications@github.com> 写道：

本項目其實只收錄字的註音，組詞的用字標準可追溯到上游項目 https://github.com/BYVoid/OpenCC。
OpenCC對這一組字的解釋爲：
https://github.com/BYVoid/OpenCC/blob/master/data/scheme/st_multi.txt#L171
如果認爲有必要調整，您可以移步 https://github.com/BYVoid/OpenCC/issues 繼續討論。
