### ISSUE TITLE
是否考慮將“眾”和“擧”用作首選字並進行類推？此二字比較貼近原字形。

### ISSUE THREAD

**Issue by i-ug-yang** [rime/rime-terra-pinyin#34]

**Comment by lotem** [comment]
​這部詞典的用字需要與OpenCC字形標準保持一致，方可準確地通過OpenCC轉換成其他字形。
您可以創建OpenCC字形到「貼近原字形」的轉換表（[舉例](https://github.com/coywjs/texts)）實現所求。
