### ISSUE TITLE
中英混输方案rime-easy-en兼容性问题

### ISSUE THREAD

**Issue by nullmax** [rime/rime-terra-pinyin#36]
我使用的是以下中英混输方案：
**https://github.com/BlindingDark/rime-easy-en**
在以下场景下出现了兼容性问题：
比如我想输入首字母大写的Fast，按Shift+f的时候直接就把F打出来了，后面的ast就连不上了。
而明月拼音就不会出现这样的问题，这个算是feature还是bug呢，或者有开关能关掉这个特性呢。

**Comment by lotem** [comment]
是​該方案設置成這樣的。
