### ISSUE TITLE
增加一些單字的臺灣讀音

### ISSUE THREAD

**Issue by dqwyy** [rime/rime-terra-pinyin#37]
危 wei2
汐 xi4
綜 zong4
壑 huo4
堤 ti2
懾 zhe2
謅 zou1
隼 zhun3
擷 jie2
拎 ling1
劊 kuai4
檜 kuai4
圳 zun4
蟄 zhi2
琊 ye2
艘 sao1
亳 bo4
偽 wei4
剖 pou3
剽 piao4
噸 dun4
坊 fang2
姣 jiao3
寂 ji2
惋 wan4
拙 zhuo2
咄 duo4
播 bo4
擁 yong3
昔 xi2
昔 cuo4
樸 pu2
濤 tao2
熄 xi2
究 jiu4
築 zhu2
綏 sui1
縛 fu2
署 shu4
菽 shu2
薇 wei2
藩 fan2
諷 feng4
諷 feng1
蹈 dao4
蹟 ji1
蹬 deng4
辱 ru4
銨 an1
銻 ti4
頗 po3
馴 xun2
緝 qi4

悄 qiao1

參考[海峽兩岸漢語發音差異列表](https://zh.wikipedia.org/wiki/%E6%B5%B7%E5%B3%BD%E5%85%A9%E5%B2%B8%E6%BC%A2%E8%AA%9E%E7%99%BC%E9%9F%B3%E5%B7%AE%E7%95%B0%E5%88%97%E8%A1%A8)和萌典。
早該做了，我等了5年，至今（2021.08.05版本）還沒人把這些讀音加進去，而我苦於不會程式碼無法下手，現列舉出來，請能者代勞。至於詞組的，很多只有臺灣讀音沒有大陸讀音，那個因為手工工作量太大，我就幫不了了，而且那個理論上似乎可以通過自動化程式完成。

另外我一直有個疑問，詞組在dict裡面是一定要加拼音嗎，例如說只有`危險 wei2 xian3`，那麼就需要在其下方另起一行加上`危險 wei1 xian3`，那能不能直接就是寫成`危險`這樣單一行呢？

**Comment by LEOYoon-Tsaw** [comment]
提pull啊大哥

**Comment by dqwyy** [comment]
我不知如何利用自動化工具準確地把字插入到它應在的位置，所以需要懂編程的用家代勞。
