### ISSUE TITLE
Can't type traditional character 著 [zhe5]

### ISSUE THREAD

**Issue by nimser** [rime/rime-terra-pinyin#43]
I can't manage to type the traditional character 著 [zhe5]. Only the simplified variant 着 is available.
Seems related to #42, but I would need someone fluent in Chinese to confirm.
(feel free to translate this issue to chinese)

**Comment by LEOYoon-Tsaw** [comment]
Rime has its own standard for traditional Chinese, since the standard for TW, HK may differ. If you want TW version, this can do it:
```
simplifier:
  opencc_config: t2tw.json # t2hk.json, t2jp.json, t2s.json should also be available
```
In vanila Rime, 著 is for bookwritting(zhu4), 着 for to wear(zhuo2), to suffer from(zhao2) modal particle(zhe5)

**Comment by nimser** [comment]
> ```
> simplifier:
>   opencc_config: t2tw.json # t2hk.json, t2jp.json, t2s.json should also be available
> ```

Thanks! I'm unsure where to put this configuration. Any advice?

**Comment by nimser** [comment]
Ok, found I had to edit the config in `/usr/share/rime-data/terra_pinyin.schema.yaml`

Then run `sudo rime_deployer --build .` in `/usr/shar/rime-data/` and restart rime. The charracter would then not be automatically be substituted, but would appear in the the options *in the very last page of suggestions*.
Quite unintuitive, but after selecting it a few times, it now comes up when I need it.

The exact config I'm using is: 

in the `engine` section:
```
    #    - simplifier                 <-- replace this line by the following
    - simplifier@zh_tw
```
And add a `simplifier` section: 
```
simplifier:
  opencc_config: t2tw.json
  option_name: zh_tw
```
