### ISSUE TITLE
Add the possibility of filtering characters of tone 5 (attenuated tone)

### ISSUE THREAD

**Issue by nimser** [rime/rime-terra-pinyin#44]
The specificity of rime-terra-pinyin is the possibility to filter characters using tone marks, represented by `-` (tone 1) `\` (tone 2) `<` (tone 3) `\` (tone 4).
Similarly, it would be great to be able to filter characters matching tone 5, for example 著/着 [zhe5]. 

Is that a feature that has been considered?

**Comment by LEOYoon-Tsaw** [comment]
You can add a `speller/algebra` to convert anything ending with `5` to some key you choose.

**Comment by lotem** [comment]
Second Leo's answer.
A realistic yet complex example is https://github.com/rime/rime-bopomofo

The current setup of `terra_pinyin` is mimicking the usage of tone marks in written form pinyin, where tone 5 is denoted without accent mark.
